### ISSUE TITLE
No problem with configuration , but it do not work in fact

### ISSUE THREAD

**Issue by Chocolate1949** [mmastrac/iterm2-zmodem#22] opened 2017-06-21 07:46 UTC
Probably，you need change execution right: 

chmod u+x iterm2-send-zmodem.sh 
chmod u+x iterm2-recv-zmodem.sh

**Comment by sunblowing** [comment] 2017-06-23 09:54
Me too.The shell script can be executed,but it doesn't work.
The version of MacOs is 10.12.5 and the version of iterm2 is 3.0.13.

**Comment by boneylw** [comment] 2017-06-28 11:23
I have the same problem in MacOS 10.12.5 with iterm2 3.0.15.

**Comment by jasonzhusmile** [comment] 2017-06-30 02:14
I have the same problem.  Iterm version: Build 3.0.15    os: 10.12.5 (mac book pro)   The two scripts are executable. Anyone can help?

**Comment by houshunwei** [comment] 2017-07-24 09:01
same problem

**Comment by gotodoit** [comment] 2017-07-27 02:52
When I enter sz or rz, I can open my window ,but file can't transfer to my mac , I have the problem on MacOS 10.12.6 with iterm2 3.0.15. It's work well a few days ago when my MacOS is 10.12.5.

**Comment by cfxmj2014** [comment] 2017-08-01 02:38
sz worked fine,but rz still get some problem

**Comment by hzgoin** [comment] 2017-08-18 06:31
@gotodoit i met the same problem as you did,but my macos is 10.12.5. it also doesnt work.

**Comment by sheepbao** [comment] 2017-08-22 05:03
same problem

**Comment by wangyaoxu** [comment] 2017-08-28 03:46
same problem. Mac 10.12.6. iterm2 3.0.15

**Comment by FashionVon** [comment] 2017-09-05 10:45
same problem .mac 10.12.6 and iterm2 3.1.beta.9 .

**Comment by xieyx** [comment] 2017-09-21 03:27
me too

**Comment by HelloLyfing** [comment] 2017-09-21 09:55
1. First, make sure you can run these two scripts:
```
# run it in your mac iterm2
/usr/local/bin/iterm2-recv-zmodem.sh
# run it 
/usr/local/bin/iterm2-send-zmodem.sh
```
You should see mac popups a file select window each time.

2. Make sure your trigger  config is valid, double check Tigger -> Parameters and Action are set  correctly.

**Comment by muzixinly** [comment] 2017-10-10 09:08
same problem .mac 10.13 and iterm2 3.1.4.beta.1
for more，when i exec the two scripts in my mac, it works fine. But when i exec on the produciton machine, it failed

**Comment by vincent927** [comment] 2017-11-02 05:53
same problem MacOS 10.12.6  iTerm2 Build 3.1.4.beta.1

**Comment by Bravoyk** [comment] 2017-11-03 11:55
me too. so what should i can do?

**Comment by PathricLee** [comment] 2017-11-14 06:39
me too, the same problem.

**Comment by PathricLee** [comment] 2017-11-14 06:39
this doesnt work.

**Comment by hzgoin** [comment] 2017-11-14 11:32
@all
the solution is: dont use expect script login your remote machine。
i found the answer here:   https://github.com/mmastrac/iterm2-zmodem/issues/19#issuecomment-315019833

**Comment by Bravoyk** [comment] 2017-11-14 13:27
@hzgoin Nope, I have tried,but It's also doesn't work.

**Comment by zeropointer** [comment] 2017-11-29 03:24
@hzgoin   yeah, your solution does work on my host with os x 10.13.1 & iterm2 Build 3.1.5 
i used expect script to login my remote host, and sz, rz doesn't work with this.  then i tried login remote host without expect script, it does work.
thank you

**Comment by shuzhou** [comment] 2017-11-30 05:36
Is there a way that I can use expect script auto login and sz/rz both?

**Comment by ryanqy** [comment] 2017-12-01 08:19
it works when don't use the expect login

**Comment by maxslug** [comment] 2018-01-14 05:49
Works for me outside of tmux, but not inside.  macOS 10.13.2 iTerm2 3.1.1

**Comment by lin879947361** [comment] 2018-04-12 16:25
I follow the Readme，and I am sure  can run the two scripts.When I use sz/rz,I can open my window ，and I can receive "Sent ->",but file can't transfer to my mac in fact.   I didn't use expect.  macOS 10.13.4 iTerm2 3.1.5

**Comment by liugang585570** [comment] 2018-05-03 16:24
same problem.

**Comment by mmastrac** [comment] 2018-05-23 20:33
Marking as a dupe of #25 to clean up issue tracker - needs more debugging as to specific reasons.

**Closed by mmastrac** 2018-05-23 20:33 UTC

**Comment by Ballieas** [comment] 2018-10-24 11:17
It works without expect script, thank u @hzgoin

**Comment by jhh130910** [comment] 2019-04-06 10:59
Problem : mac 10.14  
Linux using sz rz ( install by brew )
iterm2  using error likely below :
```
rz
z waiting to receive.**B0100000023be50
```
help me ...

**Comment by yuemanly** [comment] 2019-04-17 08:04
> Problem : mac 10.14
> Linux using sz rz ( install by brew )
> iterm2 using error likely below :
> 
> ```
> rz
> z waiting to receive.**B0100000023be50
> ```
> help me ...

@jhh130910
Maybe `expect` is the reason why lrzsz can't be used, because I had the same problem, and I just fix it. When I don't use `expect` for ssh auto-logging, the lrzsz works.
