### ISSUE TITLE
can not work with 'expect'

### ISSUE THREAD

**Issue by PlayingJoker** [mmastrac/iterm2-zmodem#24] opened 2018-01-05 07:56 UTC
I'm using a jumpserver for auto connect server, wrote a expect script like this:
```
#!/usr/bin/expect
set password fweFG@#F!FE
set timeout -1

spawn ssh -i ~/Documents/pems/server.pem jump@192.168.6.155
expect "*passphrase*"
send "$password\r"
interact
```
then it can't work anymore.
but can work without expect.

example:
ssh -i ~/Documents/pems/server.pem jump@192.168.6.155
Enter passphrase for key '/Users/joker/Documents/pems/liuzn.pem':

**Comment by ritahunter** [comment] 2018-01-08 13:47
me too. We write a script to login server using 'expect' without password input. BUT rz, sz will fail. The command will succeed, and can't find the file is... so pls help~

**Comment by fcbruce** [comment] 2018-02-26 07:01
the same problem met.

**Comment by fcbruce** [comment] 2018-02-26 08:09
@PlayingJoker @ritahunter Hi, I found the solution that we can use zssh instead of ssh

**Comment by misskeyjoy** [comment] 2018-05-20 14:57
me to. I debug find the  problem.

**Comment by mmastrac** [comment] 2018-05-23 20:22
Marking as dupe of #25 to clean up issue tracker.

**Closed by mmastrac** 2018-05-23 20:22 UTC

**Comment by biuge** [comment] 2019-01-31 10:51
> @playingjoker @ritahunter Hi, I found the solution that we can use zssh instead of ssh

老铁你是怎么做的 我也是zsh下写exp脚本 然后rz失败
