### ISSUE TITLE
It doesn't work in tmux

### ISSUE THREAD

**Issue by ThomsonTang** [mmastrac/iterm2-zmodem#14] opened 2017-01-04 09:42 UTC
It does not work in tmux although I use the `-e` option to `rz`/`sz` commands. But it's fine if I don't use `tmux` in iterm2.

**Comment by jiahut** [comment] 2017-08-07 05:45
@ThomsonTang   me too.

item2: `Build 3.0.15`
macOs: `10.12.6`

**Comment by maxslug** [comment] 2018-01-14 05:50
+1 Works for me outside of tmux, but not inside.  macOS 10.13.2 iTerm2 3.1.1 .  I'm using tmux integration mode FWIW.

**Comment by cmingxu** [comment] 2018-01-16 03:29
same issue here

**Comment by mmastrac** [comment] 2018-05-23 20:22
Marking as dupe of #25 to clean up issue tracker.

**Closed by mmastrac** 2018-05-23 20:22 UTC
